
apiVersion: 1
providers:
  - name: 'obs-lab'
    orgId: 1
    folder: 'Obs-Lab'
    type: file
    disableDeletion: false
    updateIntervalSeconds: 30
    allowUiUpdates: true
    options:
      path: /var/lib/grafana/dashboards
